import { ArrowRight } from 'lucide-react'
import { diagnosisSummary, metricLabel, timeLabel, visibleEvents, type Scenario, type WorkspaceState } from '../model'
import { useWorkspace } from '../store'
import { suiteChecks } from '../suite'
import { MetricChart } from './MetricChart'

export function Explanation({ scenario, workspace }: { scenario: Scenario; workspace: WorkspaceState }) {
  const { cursor, set, focus } = useWorkspace()
  const events = visibleEvents(scenario, cursor)
  const incident = events.some(event => event.kind === 'detect')
  const proposed = events.some(event => event.kind === 'reason')
  const production = workspace.environments[0]
  const reading = production.nodes[scenario.targetId]
  const conclusion = diagnosisSummary(scenario, workspace)
  const go = (environmentId: string) => { focus(environmentId); set({ view: 'investigation' }) }
  return <div className="explanation-page">
    <section className="why-intro"><div><span className="overline">WHAT WE KNOW · {timeLabel(cursor)}</span><h2>{workspace.verdict ? conclusion : incident ? 'We see the failure. We are still testing the cause.' : 'Start with a healthy reference.'}</h2><p>{workspace.verdict ?? (incident ? `${scenario.targetId} is showing high latency and errors. Those symptoms alone cannot tell us whether retries are sustaining the overload or the dependency has lost capacity.` : 'There is no incident recorded yet. These measurements show how the system normally behaves.')}</p></div><button className="secondary-button" onClick={() => go('production')}>Watch the agents in 3D <ArrowRight size={14} /></button></section>
    <section className="why-signals" aria-label="Production symptoms">{[['Dependency latency', metricLabel(reading?.latency, 'ms'), `Healthy reference: ${metricLabel(scenario.baseline[scenario.targetId]?.latency, 'ms')}`], ['Error rate', metricLabel(reading?.errorRate, '%'), 'Requests reporting an error'], ['Issued load', metricLabel(reading?.qps, 'qps'), 'Includes repeated requests']].map(([label,value,note]) => <div key={label}><span>{label}</span><strong>{value}</strong><small>{note}</small></div>)}</section>
    <section className="why-chart panel"><div className="panel-title"><div><span className="overline">WHAT CHANGED IN PRODUCTION</span><h3>{scenario.targetId}</h3></div><span className="chart-legend"><i className="latency-line" />Latency · ms<i className="load-line" />Load · qps</span></div><MetricChart scenario={scenario} cursor={cursor} environmentId="production" nodeId={scenario.targetId} /><p className="chart-footnote">Shaded spans show interventions. Only evidence available at this replay time is shown. {scenario.live ? 'Readings come from recorded C1 windows and C4 audit events.' : 'All values are simulated.'}</p></section>
    {scenario.live && <section className="why-hypothesis panel"><span className="overline">ELASTIC RETRIEVAL · READ ONLY</span><h2>Similar incidents</h2>{scenario.similarIncidents?.length ? <><p>Historical matches provide context only. Their labels never decide this incident’s verdict.</p><dl>{scenario.similarIncidents.map(match => <div key={match.incident_id}><dt>Looks like {match.incident_id}</dt><dd>Similarity {Math.round(match.score * 100)}%{match.diagnosis ? ` · prior verdict: ${match.diagnosis}` : ''}{match.confirmed === true ? ' · confirmed' : ''}{match.matching_metrics?.length ? ` · metrics: ${match.matching_metrics.join(', ')}` : ''}{match.recipe ? ` · replay: ${match.recipe}` : ''}</dd></div>)}</dl></> : <p className="chart-footnote">No matching fingerprints were returned for this incident.</p>}</section>}
    <section className="why-method"><span className="overline">WHY INTRODUCE A FAILURE?</span><h2>To find out which explanation survives a test.</h2><p>A chart can show that the system is overloaded without explaining why. We introduce one controlled change in a clean clone, then check whether it produces the same symptoms. Next, we cap retries and remove the cap. The two possible causes predict different responses.</p><ol className="why-flow"><li><b>Reproduce</b><span>Can the suspected cause create these symptoms?</span></li><li><b>Probe</b><span>What changes when we limit retries?</span></li><li><b>Release</b><span>Does recovery last when retries return?</span></li><li><b>Confirm</b><span>Does production respond as predicted?</span></li></ol><p className="why-boundary">Clone experiments use isolated state and reversible changes. A matching clone result keeps a theory in play; it does not prove what caused the production incident.</p></section>
    <div className="why-comparisons">{proposed ? scenario.hypotheses.map(hypothesis => {
      const envId = events.find(event => event.kind === 'clone' && event.environment?.hypothesisId === hypothesis.id)?.environmentId
      const environment = workspace.environments.find(env => env.id === envId)
      const perturbation = events.find(event => event.environmentId === envId && event.tool === 'lab.apply')
      const checks = envId ? suiteChecks(scenario, envId, cursor) : []
      return <section className="why-hypothesis panel" key={hypothesis.id}><span className="overline">POSSIBLE CAUSE {hypothesis.id}</span><h2>{hypothesis.title}</h2><p>{hypothesis.description}</p><dl><div><dt>Chaos test</dt><dd>{perturbation?.title ?? 'No clone action recorded yet.'}</dd></div><div><dt>Why this test?</dt><dd>{perturbation?.prediction ?? hypothesis.description}</dd></div><div><dt>What would we expect?</dt><dd>{hypothesis.prediction}</dd></div><div><dt>At this point</dt><dd>{perturbation ? `The change was applied at ${timeLabel(perturbation.at)} with a ${perturbation.action?.ttl}s time limit.` : 'The change has not been applied yet.'}</dd></div></dl>
        <div className="why-checks">{checks.map(check => <details key={check.id}><summary><i className={check.state === 'passed' ? 'passed' : ''} /><span>{check.label}</span><small>{check.state === 'passed' ? 'Passed' : check.state === 'running' ? 'Running' : check.state === 'failed' ? 'Failed' : 'Not run'}</small></summary><p>{check.description}</p>{check.event?.testResult && <p><b>Result:</b> {check.event.testResult.observed}</p>}</details>)}</div>
        {environment && envId ? <><h3 className="why-chart-label">How {environment.label} responded</h3><MetricChart scenario={scenario} cursor={cursor} environmentId={envId} nodeId={scenario.targetId} /><button className="text-button" onClick={() => go(envId)}>Watch this agent <ArrowRight size={14} /></button></> : <p className="chart-footnote">{events.some(event => event.environmentId === envId && event.kind === 'archive') ? 'Clone archived. Its test results are retained above.' : 'The clone has not been created yet.'}</p>}
      </section>
    }) : <p className="empty-copy">Possible causes will appear when the agent has reviewed the incident.</p>}</div>
    <section className="why-conclusion"><span className="overline">WHAT CAN WE CONCLUDE?</span><h2>{conclusion}</h2><p>{workspace.verdict ?? 'Passing clone tests tells us whether our predictions match those experiments. We still need a measured production response before choosing a cause.'}</p>{workspace.confirmed && <p>A confirmed diagnosis does not by itself establish that mitigation or repair is complete.</p>}</section>
  </div>
}
