import { expect, test } from '@playwright/test'

test('renders the real WebGL scene and a clearly marked, interactive prototype', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await expect(page.getByText('Simulated data', { exact: true })).toBeVisible()
  await expect(page.locator('.map-canvas canvas')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Inspect primary-db in Production', exact: true })).toBeVisible()
  await page.waitForTimeout(1800)
  await page.screenshot({ path: 'test-results/workspace-desktop.png', fullPage: true })
  await page.getByRole('button', { name: 'Inspect primary-db in Production', exact: true }).click()
  await expect(page.getByText('ENTITY INSPECTOR', { exact: true })).toBeVisible()
  await expect(page.getByText('Instances: not collected')).toBeVisible()
  await page.getByRole('tab', { name: /Decision trace/ }).click()
  await expect(page.getByText('Scripted example · not a live model call').first()).toBeVisible()
  expect(errors).toEqual([])
})

test('seeking backward removes future environments and evidence', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('combobox', { name: 'Selected environment' }).locator('option')).toHaveCount(3)
  await page.getByRole('button', { name: 'Restart simulation' }).click()
  await expect(page.getByRole('combobox', { name: 'Selected environment' }).locator('option')).toHaveCount(1)
  await expect(page.getByText('WORKING HYPOTHESES', { exact: true })).not.toBeVisible()
  await page.getByRole('button', { name: 'Play simulation' }).click()
  await expect(page.getByRole('button', { name: 'Pause simulation', exact: true }).last()).toBeVisible()
  await page.getByRole('button', { name: 'Pause simulation', exact: true }).last().click()
  const before = await page.getByRole('slider', { name: 'Simulation timeline' }).inputValue()
  await page.waitForTimeout(500)
  expect(await page.getByRole('slider', { name: 'Simulation timeline' }).inputValue()).toBe(before)
})

test('supports a second arbitrary architecture, flat view, metrics, and safe draft controls', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('combobox', { name: 'Example architecture' }).selectOption('pipeline')
  await page.getByRole('button', { name: 'Show flat topology' }).click()
  await expect(page.getByTestId('flat-topology')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Inspect events in Production', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Observability', exact: true }).click()
  await page.getByRole('textbox', { name: 'Filter services' }).fill('admin-api')
  await expect(page.locator('tbody tr')).toHaveCount(1)
  await expect(page.locator('tbody tr')).toContainText('Not collected')
  await page.getByRole('button', { name: 'New experiment', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByRole('button', { name: 'Validate draft' }).click()
  await expect(page.getByRole('status')).toContainText('Nothing was submitted or persisted')
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Safety & approvals' }).click()
  await expect(page.getByRole('button', { name: /Approval unavailable/ })).toBeDisabled()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).not.toBeVisible()
})

test('keeps mobile content in the viewport and respects reduced motion', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await page.getByRole('button', { name: 'Show flat topology' }).click()
  await expect(page.getByTestId('flat-topology')).toBeVisible()
  await page.screenshot({ path: 'test-results/workspace-mobile.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'New experiment', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
})
